@startuml

|Лорд Фаркуад|
start
:Инициировать сделку;
:Отправить Шрека на миссию;

|Шрек|
:Заключить сделку;
:Взять Осла в компаньоны;

|Шрек и Осел|
:Отправиться к Башне Дракона;

|Путь|
:Преодолеть болото;
:Пройти через лес;
:Прибыть к башне;

|Сражение|
:Проникнуть в башню;
:Вступить в бой с Драконом;

fork
  :Шрек атакует Дракона;
fork again
  :Осел отвлекает Дракона;
  :Осел использует болтовню;
end fork

:Победить Дракона;

|Обнаружение|
:Найти Фиону в башне;

:Проверить время суток;

if (День?) then (да)
  :Фиона в форме Человека;
  :State = Human;
else (нет)
  :Фиона трансформируется;
  :State = Ogre;
endif

:Представиться Фионе;

while (Фиона сопротивляется?) is (да)
  :Убедить Фиону;
  :Применить дипломатию;
endwhile (нет)

:Фиона соглашается на спасение;

|Уход|
:Покинуть башню;
:Обнаружить проснувшегося Дракона;
:Начать побег;

fork
  :Бежать по мосту;
fork again
  :Создавать препятствия;
  :Осел отвлекает Дракона снова;
end fork

:Успешно скрыться от Дракона;

|Передача|
:Доставить Фиону к Лорду Фаркуаду;

:Передать Фиону;

if (Фиона в человеческой форме?) then (да)
  :Лорд Фаркуад принимает Фиону;
  :Сделка завершена успешно;
else (нет)
  :Лорд Фаркуад нарушает сделку;
  :Конфликт;
endif

stop

@enduml
