@startuml

state Фиона {
    [*] --> Человек
    
    state Человек {
        [*] --> ДневноеСостояние
        ДневноеСостояние : являетсяОгром = false
    }
    
    state Огр {
        [*] --> НочноеСостояние
        НочноеСостояние : являетсяОгром = true
    }
    
    Человек --> Огр : Заход солнца\nтрансформироваться()
    Огр --> Человек : Восход солнца\nтрансформироваться()
}

@enduml
